### ISSUE TITLE
Running the code model_flops = flops.total () will result in an assertion error？

### ISSUE THREAD

**Issue by liaochuanlin** [Amshaker/unetr_plus_plus#56] opened 2023-09-17 07:53 UTC
Traceback (most recent call last):
File "../unetr_pp/run/run_training.py", line 171, in
main()
File "../unetr_pp/run/run_training.py", line 142, in main
trainer.initialize(not validation_only)
File "/home/lcl/unetr_plus_plus/unetr_pp/training/network_training/unetr_pp_trainer_tumor.py", line 150, in initialize
self.initialize_network()
File "/home/lcl/unetr_plus_plus/unetr_pp/training/network_training/unetr_pp_trainer_tumor.py", line 189, in initialize_network
model_flops = flops.total()
File "/home/lcl/anaconda3/envs/unetr_pp/lib/python3.8/site-packages/fvcore/nn/jit_analysis.py", line 248, in total
stats = self._analyze()
File "/home/lcl/anaconda3/envs/unetr_pp/lib/python3.8/site-packages/fvcore/nn/jit_analysis.py", line 583, in _analyze
op_counts = self._op_handles[kind](inputs, outputs)
File "/home/lcl/anaconda3/envs/unetr_pp/lib/python3.8/site-packages/fvcore/nn/jit_handles.py", line 181, in einsum_flop_jit
assert len(inputs) == 2, len(inputs)

**Comment by Amshaker** [comment] 2024-01-21 09:48
Duplicate of https://github.com/Amshaker/unetr_plus_plus/issues/55

**Closed by Amshaker** 2024-01-21 09:48 UTC
